@baseurl = http://127.0.0.1:8080/

# @name root
GET {{baseurl}} HTTP/1.1
content-type: application/json

###

# @name create-dino
POST {{baseurl}}animals HTTP/1.1
content-type: application/json
# Authorization: {{token}}

{
    "name":"cheetah", 
    "weight": 200, 
    "diet":"carnivorous"
}

###

# @name get-all-dinos
GET {{baseurl}}animals HTTP/1.1
content-type: application/json

###

# @name get-dino-by-name
GET {{baseurl}}animals/590c11e1-333f-45ae-b073-5e80bf3beaae HTTP/1.1
content-type: application/json

###

# @name update-dino-by-name
PUT {{baseurl}}animals/590c11e7-333f-45ae-b073-5e80bf3beaae HTTP/1.1
content-type: application/json

{
    "name":"t-rexx", 
    "weight": 5000, 
    "diet":"carnivorous"
}

###

# @name delete-dino-by-name
DELETE {{baseurl}}animals/one HTTP/1.1
content-type: application/json

###
