version: "3.8"
services:
  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kevpy
      POSTGRES_DB: dinos_db
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  db_data:
